name: DevOps Demo CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Test File Existence
      run: test -f index.html

    - name: Build Test Docker Image
      run: docker build -t devops-test .